### PR TITLE
fix(assembly): Optimized ByteReader serializer

### LINKED ISSUE #462: Optimize bytes serializer for Assembly
Currently, the bytes serializer users internally an allocated `Vec<u8>`

This allocation is not necessary and it could work with a slice of bytes in order to optimize its runtime overhead

https://github.com/maticnetwork/miden/blob/4553652a2a91e269d085415ebbe1cc3e49b715ba/assembly/src/parsers/ast/mod.rs#L59

_Originally posted by @bobbinth in https://github.com/maticnetwork/miden/pull/461#discussion_r1012527541_

### PR DESCRIPTION
**Pull request by amankrx**
## Describe your changes
Updated the ByteReader to work with slices rather than vectors. Also, fixed a minor typo in the serializer. Please review it to see if this works, or if I would have to make some additional changes.

Resolves #462 

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
Looks great! Thank you!

**Comment by bobbinth** [comment]
@amankrx - could you make the tiny rustfmt fix? I'll merge after that.

**Comment by amankrx** [comment]
Ohh sorry, I missed that. I should squash my commits as well right?

**Comment by bobbinth** [comment]
No worries! Yes, as single commit for this PR is fine.

**Pull request merged**
