### PR TITLE
Remove `EQW` vm  instruction

### PR DESCRIPTION
**Pull request by 4rgon4ut**
This PR addresses https://github.com/maticnetwork/miden/issues/320.

- Removed `EQW` instruction from the VM.
- Emulated `EQW` operation using other VM instruction in the assembly.
- Updated the docs/cycle count of the impacted operations.

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
All looks great! Thank you!

**Comment by bobbinth** [comment]
Only one small comment: could you squash commits so that this PR has just a couple of them?

**Comment by 4rgon4ut** [comment]
@bobbinth Done. My bad with merge from `next`, sorry.

**Review by bobbinth — APPROVED** [review]
No worries! Thank you!

**Pull request merged**
