### PR TITLE
Add changelog for v0.1.0 - v0.3.0

### PR DESCRIPTION
**Pull request by grjte**
This PR adds an initial changelog using the information from the past 2 releases and a draft of updates for v0.3 (not yet released).

Please let me know what other things you think should be included in the v0.3 release notes. I didn't include info about the new assembler changes yet - I'm not sure which things you want to add in.

### CODE REVIEW

**Comment by bobbinth** [comment]
Thank you! A few other things worth mentioning:

* Assembler refactoring and support for module providers (this is a breaking change since `stdlib` is no longer available by default).
* New `caller` instruction (could be mentioned in the same bullet point as `syscall`).
* New `adv.mem` decorator for copying memory regions into advice map.
* Implemented AIR constraints for the stack component.

**Comment by grjte** [comment]
>     * Implemented AIR constraints for the stack component.

If we're including this, should we add items to v0.2.0 about the AIR constraints that were previously implemented? (I had actually just left this item off for consistency and because it's not strictly user-facing, so I wasn't sure if you wanted it.)

**Comment by grjte** [comment]
I've added the suggested changes

**Review by bobbinth — APPROVED** [review]
All looks good! Thank you!

**Pull request merged**
