### PR TITLE
docs(mdbook): update co-processor diagrams to show internal selectors

### PR DESCRIPTION
**Pull request by 0xKanekiKen**

### CODE REVIEW

**Review by grjte — CHANGES_REQUESTED** [review]
@0xKanekiKen I think this is really a huge improvement in clarity, great work.

One very nitty request - the end of the hasher selectors should actually be aligned with the end of the bitwise/pow2 selectors, since the last selector of the hasher and the last selector of the bitwise/pow2 are actually in the same column of the auxiliary table. Can you adjust that alignment to make that clear?

**Comment by grjte** [comment]
@0xKanekiKen you'll also need to rebase and update the asset locations once #257 is merged

**Comment by 0xKanekiKen** [comment]
@grjte: Thanks for the heads up. I'm looking forward to the merge.

**Review by bobbinth — APPROVED** [review]
All looks good! Thank you!

**Review by bobbinth — APPROVED** [review]

**Pull request merged**
