### PR TITLE
Add cycle count column in assembly operation table

### PR DESCRIPTION
**Pull request by 0xKanekiKen**
This PR addresses the second part of #351.

### CODE REVIEW

**Comment by 0xKanekiKen** [comment]
@bobbinth -  @grjte and I have come up with the following way to show assembly operation cycle count in the mdbook. Please let us know you thoughts on it.

Screenshot from 2022-08-08 12-20-46

u23_arithmetic_ops

One other way would be to introduce a separate column for VM cycles in the table. It though makes the table a bit crowded and messes up the formula. 
Screenshot from 2022-08-08 09-26-43

**Comment by bobbinth** [comment]
I like this approach! And I agree that separate column makes it look worse.

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I'm guessing `mtree_*` instruction cycle counts already reflect changes form #343 - right?

**Comment by 0xKanekiKen** [comment]
Yes! The cycle counts have been updated.

**Pull request merged**
