### PR TITLE
Number Theoretic Transform using Miden Assembly

### PR DESCRIPTION
**Pull request by itzmeanjan**
- [x] Implement Number Theoretic Transform (NTT) for a vector of length 512 s.t. each element ∈ Zp | p = 2^64 - 2^32 + 1.
- [x] Implement inverse NTT for vector of same length

---

- Note, output of NTT is kept in bit reversed order. 
- So inverse NTT implementation should consider that & finally produce output vector in standard order.

---

See benchmark details [here](https://github.com/maticnetwork/miden/pull/349#issuecomment-1231324185)

### CODE REVIEW

**Comment by bobbinth** [comment]
Awesome work! Thank you! One comment:

I noticed that sometimes we have `pushw` followed by `popw` as in the example below:
```
pushw.local.0
pushw.local.64
push.18446462594437873665.18446462594437873665.18446462594437873665.18446462594437873665

exec.butterfly

popw.local.64
popw.local.0
```
It should be possible to re-write this using `loadw` and `storew` instructions, and that would probably save about 10 cycles.

**Comment by itzmeanjan** [comment]
> Awesome work! Thank you! One comment:
> 
> I noticed that sometimes we have `pushw` followed by `popw` as in the example below:
> 
> ```
> pushw.local.0
> pushw.local.64
> push.18446462594437873665.18446462594437873665.18446462594437873665.18446462594437873665
> 
> exec.butterfly
> 
> popw.local.64
> popw.local.0
> ```
> 
> It should be possible to re-write this using `loadw` and `storew` instructions, and that would probably save about 10 cycles.

Thanks @bobbinth for the suggestion. 

I rewrote it using `{loadw, storew}.local.*` instructions, seeing ~14.54% performance improvement.

At commit 2cf924e, cost of NTT-512: **46435** cycles

**Comment by itzmeanjan** [comment]
Commit 8258d90, brought in latest from `next`. Updated `assert.eq` instruction to `assert_eq`.

**Comment by itzmeanjan** [comment]
At commit 5bee802,

- cost of NTT512 47403 cycles
- cost of iNTT512 52426 cycles

**Review by bobbinth — CHANGES_REQUESTED** [review]
@itzmeanjan Looks great! Thank you!

I can't leave comments inline as the file is a bit too larger - but I'm wondering if we can refactor this to keep the inner loops (rather than unrolling them). For example, in the following code, it seems like we are tracking two indexes: i which starts at 0, and j which starts at 32:

```
storew.local.32
swapw
storew.local.0

loadw.local.1
swapw
loadw.local.33
push.1099511627520.1099511627520.1099511627520.1099511627520

exec.butterfly

storew.local.33
swapw
storew.local.1

loadw.local.2
swapw
loadw.local.34
push.1099511627520.1099511627520.1099511627520.1099511627520

exec.butterfly
```
Instead of keeping these two indexes, we could keep the absolute memory address on the stack and increment them (using `incr` instruction). In terms of cycle count, it shouldn't be much worse than the current approach.

We can still keep the outer loops unrolled, but if we can keep the inner loops in loop form, this will reduce the amount of code and should make executing programs faster as there will be fewer things to hash.

Also, it looks like the code above could avoid pushing roots of unity onto the stack after every call to `butterfly` procedure if the procedure didn't remove them from the stack. If this works, this could save quite a few cycles.

**Comment by itzmeanjan** [comment]
> @itzmeanjan Looks great! Thank you!
> 
> I can't leave comments inline as the file is a bit too larger - but I'm wondering if we can refactor this to keep the inner loops (rather than unrolling them). For example, in the following code, it seems like we are tracking two indexes: i which starts at 0, and j which starts at 32:
> 
> ```
> storew.local.32
> swapw
> storew.local.0
> 
> loadw.local.1
> swapw
> loadw.local.33
> push.1099511627520.1099511627520.1099511627520.1099511627520
> 
> exec.butterfly
> 
> storew.local.33
> swapw
> storew.local.1
> 
> loadw.local.2
> swapw
> loadw.local.34
> push.1099511627520.1099511627520.1099511627520.1099511627520
> 
> exec.butterfly
> ```
> 
> Instead of keeping these two indexes, we could keep the absolute memory address on the stack and increment them (using `incr` instruction). In terms of cycle count, it shouldn't be much worse than the current approach.
> 
> We can still keep the outer loops unrolled, but if we can keep the inner loops in loop form, this will reduce the amount of code and should make executing programs faster as there will be fewer things to hash.
> 
> Also, it looks like the code above could avoid pushing roots of unity onto the stack after every call to `butterfly` procedure if the procedure didn't remove them from the stack. If this works, this could save quite a few cycles.

Just finished rewriting unrolled loops as repeat loop structures. Reduced from ~18k LOC to ~2.2k LOC.

> LOC -> Lines of Code

At commit bb364b2,

NTT-512: 65,917 cycles
iNTT-512: 71,091 cycles

**Comment by itzmeanjan** [comment]
> At commit [bb364b2](https://github.com/maticnetwork/miden/commit/bb364b20cfab35c17635b9f0052a44b18312bda8),
> 
> NTT-512: 65,917 cycles iNTT-512: 71,091 cycles

At commit 70778a7a2f4dc9a30436e0f4208f88b16f53f29b,

NTT-512 costs: 64,913 cycles
iNTT-512 costs: 69,992 cycles

Read commit message for getting a better understanding of how it was achieved.

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

Some thoughts for the future. Once we have an efficient way of populating memory (as described in #336), we should be able to reduce cycle count quite a bit by putting all roots of unity (in desired order, and with duplicates) into memory (instead of the stack).

**Comment by itzmeanjan** [comment]
> Some thoughts for the future. Once we have an efficient way of populating memory (as described in #336), we should be able to reduce cycle count quite a bit by putting all roots of unity (in desired order, and with duplicates) into memory (instead of the stack).

That'll be great !

**Pull request merged**
