### PR TITLE
Keccak256 in Miden Assembly

### PR DESCRIPTION
**Pull request by itzmeanjan**
## Progress

- [x] `θ`; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/sha3.hpp#L55-L98)
- [x] `ρ`; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/sha3.hpp#L115-L147)
- [x] `π`; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/sha3.hpp#L169-L207)
- [x] `χ`; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/sha3.hpp#L233-L271)
- [x] `ι`; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/sha3.hpp#L288-L306)
- [x] round; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/sha3.hpp#L325-L342)
- [x] keccak-p[1600, 24]; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/sha3.hpp#L379-L427)
- [x] keccak256 hash function; see [here](https://github.com/itzmeanjan/merklize-sha/blob/1d35aae9da7fed20127489f362b4bc93242a516c/include/keccak_256.hpp#L232-L257)

### CODE REVIEW

**Comment by itzmeanjan** [comment]
VM cycle count for applying keccak-p[1600, 24]: **134,355**

**Comment by itzmeanjan** [comment]
VM cycle count for computing keccak256 2-to-1 hash: **149,370**

**Comment by itzmeanjan** [comment]
For understanding bit interleaving technique, which is leveraged in this implementation so that using only 32 -bit bitwise operations keccak256 hash can be computed, I suggest you read section 2.1 of https://keccak.team/files/Keccak-implementation-3.2.pdf

**Review by bobbinth — CHANGES_REQUESTED** [review]
Thank you! Looks great! One small thing:

I'm assuming testing this would take quite a bit of time. Could we add the `ignore` attribute for the test so that it is run only when we want to run it explicitly? We can remove this attribute later once we improve script compilation times.

Also, some optimization thoughts for the future:

1. Once we have `u64` module fully implemented in `stdlib` we might simplify the code a bit.
2. I noticed that pattern of `popw` followed by `pushw` is used quite frequently. We could reduce the number of cycles by using `storew` followed by `loadw` instead.
3. In some cases, it might make sense to use `load` and `store` (for single elements) rather the variants for full words followed by stack manipulations.

**Comment by itzmeanjan** [comment]
Thanks for reviewing !

> I'm assuming testing this would take quite a bit of time. Could we add the `ignore` attribute for the test so that it is run only when we want to run it explicitly? We can remove this attribute later once we improve script compilation times.

Fixed here https://github.com/maticnetwork/miden/pull/154/commits/4bf82a976c4be3a7e000866df7d0278cb072e663

> Also, some optimization thoughts for the future:

Noted down, I'll apply them when I revisit the problem.

**Review by bobbinth — APPROVED** [review]
All looks good! thank you!

**Pull request merged**
